server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    password: req
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
#
#spring:
#  profiles:
#    active: dev